kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: namespace-reader
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-reader-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    apiGroup: ""
roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: ""

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: k8stargetapp-config-map
data:
  application.properties: |-
    targetapp.property1=This is the property1
    targetapp.property2=true
    targetapp.property3=57

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8stargetapp-deployment
  labels:
    app: k8stargetapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8stargetapp
  template:
    metadata:
      labels:
        app: k8stargetapp
    spec:
      containers:
        - name: k8stargetapp
          image: targetapp:0.0.2-SNAPSHOT
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: k8stargetapp-node-port
  labels:
    app: k8stargetapp
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 8080
      nodePort: 32000
  selector:
    app: k8stargetapp