apiVersion: v1
kind: Service
metadata:
  name: k8stargetapp-node-port
  labels:
    app: k8stargetapp
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 8080
      nodePort: 32000
  selector:
    app: k8stargetapp