apiVersion: v1
kind: ConfigMap
metadata:
  name: k8stargetapp-config-map
data:
  application.properties: |-
    targetapp.property1=This is the property1
    targetapp.property2=true
    targetapp.property3=57
