apiVersion: v1
kind: Service
metadata:
  name: k8stargetapp-node-port
  labels:
    app: k8stargetapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: k8stargetapp